// Generated by scripts/generate-site-catalog.py from the YAML files under sites. Do not edit.
//
// Add or change a site by editing its YAML file and re-running the script.

import Foundation

extension SiteCatalog {
	static let entries: [Entry] = [
		.init(
			name: "Flying Toasters",
			url: "https://www.bryanbraun.com/after-dark-css/all/flying-toasters.html",
			description: "The After Dark flying toasters screensaver, rebuilt in pure CSS.",
			tags: ["screensaver", "art", "ambient"],
			isLive: true,
			reloadInterval: nil,
			crop: nil,
			css: nil,
			javaScript: nil,
			requiresLogin: false
		),
		.init(
			name: "Bing Photo of the Day",
			url: "https://bing-photo-of-the-day.netlify.app",
			description: "Bing's daily featured photograph, aspect-filled to the screen.",
			tags: ["photo", "ambient"],
			isLive: false,
			reloadInterval: 21600,
			crop: nil,
			css: nil,
			javaScript: nil,
			requiresLogin: false
		),
		.init(
			name: "Cocktail Chart",
			url: "https://informationisbeautiful.net/visualizations/cocktails-interactive/",
			description: "Information Is Beautiful's chart of what actually goes into every classic cocktail.",
			tags: ["data", "art"],
			isLive: false,
			reloadInterval: 86400,
			crop: nil,
			css: nil,
			javaScript: nil,
			requiresLogin: false
		),
		.init(
			name: "Gitstalk",
			url: "https://gitstalk.netlify.app/sindresorhus",
			description: "A GitHub user's recent public activity as a card feed. Replace the username in the URL with your own.",
			tags: ["dashboard", "personal", "data"],
			isLive: false,
			reloadInterval: 1800,
			crop: nil,
			css: nil,
			javaScript: nil,
			requiresLogin: false
		),
		.init(
			name: "Google Calendar",
			url: "https://calendar.google.com/",
			description: "Your week laid over the desktop, with all of Google's chrome stripped away.",
			tags: ["calendar", "dashboard"],
			isLive: false,
			reloadInterval: 900,
			crop: nil,
			css: "* {\n  background-color: transparent !important;\n  color: white !important;\n}\n\n.QQYuzf,\n.gboEAb,\nheader.NkK3Fc,\n.Hrn1mc {\n  display: none !important;\n}\n\n[role=\"grid\"] * {\n  border-color: rgba(255, 255, 255, 0.3) !important;\n}\n\n.tNDBE:not(.Wyo4Qe),\n.SGWAac,\n.QIadxc:last-child {\n  border: none !important;\n}\n\n[data-chips-dialog] {\n  background-color: rgba(0 0 0 / 80%) !important;\n}\n",
			javaScript: nil,
			requiresLogin: true
		),
		.init(
			name: "Google Trends",
			url: "https://trends.google.com/tv/",
			description: "What the world is searching for right now, as a self-updating tile wall.",
			tags: ["data", "news", "dashboard"],
			isLive: false,
			reloadInterval: 1800,
			crop: nil,
			css: nil,
			javaScript: nil,
			requiresLogin: false
		),
		.init(
			name: "Gyroscope",
			url: "https://gyrosco.pe/",
			description: "A personal life dashboard. steps, sleep, heart rate, time tracking. on one page.",
			tags: ["dashboard", "personal", "data"],
			isLive: false,
			reloadInterval: 900,
			crop: nil,
			css: nil,
			javaScript: nil,
			requiresLogin: true
		),
		.init(
			name: "Helvetictoc",
			url: "http://www.helvetictoc.com/",
			description: "A Helvetica word clock that spells out the time in prose.",
			tags: ["clock"],
			isLive: false,
			reloadInterval: 60,
			crop: nil,
			css: "body.day, body.night {\n  background-color: transparent;\n  color: white\n}\n\ndiv.screen {\n  margin: 4%;\n  font-size: 100px !important;\n  bottom: 0;\n  top: auto;\n}\n\n#colophon { display: none }\n",
			javaScript: nil,
			requiresLogin: false
		),
		.init(
			name: "Hoodmaps",
			url: "https://hoodmaps.com/new-york-city-neighborhood-map",
			description: "A crowdsourced, opinionated map of who actually lives in each part of a city.",
			tags: ["map", "data", "art"],
			isLive: false,
			reloadInterval: 86400,
			crop: nil,
			css: nil,
			javaScript: nil,
			requiresLogin: false
		),
		.init(
			name: "Infinitown",
			url: "https://demos.littleworkshop.fr/infinitown",
			description: "An endlessly scrolling low-poly town with cars and trees, seen from above.",
			tags: ["art", "ambient", "3d", "screensaver"],
			isLive: true,
			reloadInterval: nil,
			crop: nil,
			css: "#about-button {\n  display: none;\n}\n",
			javaScript: nil,
			requiresLogin: false
		),
		.init(
			name: "Jellyfish",
			url: "https://akirodic.com/p/jellyfish/",
			description: "A translucent jellyfish drifting through dark water.",
			tags: ["art", "ambient", "3d", "screensaver"],
			isLive: true,
			reloadInterval: nil,
			crop: nil,
			css: nil,
			javaScript: nil,
			requiresLogin: false
		),
		.init(
			name: "LLM Performance Leaderboard",
			url: "https://huggingface.co/spaces/ArtificialAnalysis/LLM-Performance-Leaderboard",
			description: "Artificial Analysis's ranking of language models by speed, price and quality.",
			tags: ["data", "dashboard"],
			isLive: false,
			reloadInterval: 21600,
			crop: nil,
			css: nil,
			javaScript: nil,
			requiresLogin: false
		),
		.init(
			name: "Clouds",
			url: "https://mrdoob.com/lab/javascript/webgl/clouds/",
			description: "Slow volumetric clouds drifting across a blue sky.",
			tags: ["art", "ambient", "screensaver", "3d"],
			isLive: true,
			reloadInterval: nil,
			crop: nil,
			css: nil,
			javaScript: nil,
			requiresLogin: false
		),
		.init(
			name: "Minimal Clock",
			url: "https://time.pablopunk.com/?fg=white&bg=transparent&font=SFMono-Regular,Consolas,%27Liberation%20Mono%27,Menlo,monospace",
			description: "A plain monospace clock on a transparent background, so the wallpaper underneath shows through.",
			tags: ["clock"],
			isLive: false,
			reloadInterval: 60,
			crop: nil,
			css: nil,
			javaScript: nil,
			requiresLogin: false
		),
		.init(
			name: "Panomax Webcam",
			url: "https://panodata.panomax.com/cams/879/recent_full.jpg",
			description: "The latest frame from a Panomax panoramic outdoor webcam, served as a plain image.",
			tags: ["photo", "ambient"],
			isLive: false,
			reloadInterval: 600,
			crop: nil,
			css: nil,
			javaScript: nil,
			requiresLogin: false
		),
		.init(
			name: "Pexels Wallpaper",
			url: "https://geert.github.io/pexel-wallpaper/",
			description: "A rotating full-bleed photograph pulled from Pexels.",
			tags: ["photo", "ambient"],
			isLive: false,
			reloadInterval: 3600,
			crop: nil,
			css: nil,
			javaScript: nil,
			requiresLogin: false
		),
		.init(
			name: "Polish TV Clock",
			url: "https://aresluna.org/polish-tv-clock/",
			description: "A recreation of the clock that opened Polish state television broadcasts.",
			tags: ["clock", "art"],
			isLive: false,
			reloadInterval: 60,
			crop: nil,
			css: nil,
			javaScript: nil,
			requiresLogin: false
		),
		.init(
			name: "Random Street View",
			url: "https://randomstreetview.com/#slideshow",
			description: "A random Google Street View panorama from somewhere on Earth, new one on every reload.",
			tags: ["photo", "map", "ambient"],
			isLive: false,
			reloadInterval: 600,
			crop: nil,
			css: nil,
			javaScript: nil,
			requiresLogin: false
		),
		.init(
			name: "WeatherStar 4000+",
			url: "https://weatherstar.netbymatt.com/?kiosk=true",
			description: "A faithful emulation of the 1990s Weather Channel local forecast, US locations only.",
			tags: ["weather", "ambient", "data"],
			isLive: true,
			reloadInterval: nil,
			crop: nil,
			css: nil,
			javaScript: nil,
			requiresLogin: false
		),
		.init(
			name: "WeatherStar International",
			url: "https://mwood77.github.io/ws4kp-international/?kiosk=true",
			description: "The WeatherStar 4000+ presentation, rebuilt for locations outside the United States.",
			tags: ["weather", "ambient", "data"],
			isLive: true,
			reloadInterval: nil,
			crop: nil,
			css: nil,
			javaScript: nil,
			requiresLogin: false
		),
		.init(
			name: "WebClock",
			url: "https://findtreasureisland.github.io/clock/index.html",
			description: "A large full-screen digital clock with the date.",
			tags: ["clock"],
			isLive: false,
			reloadInterval: 60,
			crop: nil,
			css: nil,
			javaScript: nil,
			requiresLogin: false
		),
		.init(
			name: "WebGL Fluid Simulation",
			url: "https://paveldogreat.github.io/WebGL-Fluid-Simulation/",
			description: "Coloured fluid that swirls across the screen and reacts to the pointer in browsing mode.",
			tags: ["art", "ambient", "screensaver", "3d"],
			isLive: true,
			reloadInterval: nil,
			crop: nil,
			css: nil,
			javaScript: nil,
			requiresLogin: false
		),
		.init(
			name: "Windy",
			url: "https://www.windy.com/",
			description: "A live weather map. wind, rain, temperature and pressure layers over the whole globe.",
			tags: ["weather", "map", "data"],
			isLive: false,
			reloadInterval: 1800,
			crop: nil,
			css: nil,
			javaScript: nil,
			requiresLogin: false
		),
		.init(
			name: "Zoom Earth",
			url: "https://zoom.earth/maps/satellite/#view=41.989,12.766,6.23z/beta=mtg/overlays=radar,labels:off,lines:off",
			description: "Near-live satellite imagery with a rain-radar overlay and all labels turned off.",
			tags: ["weather", "map", "photo"],
			isLive: false,
			reloadInterval: 900,
			crop: nil,
			css: nil,
			javaScript: nil,
			requiresLogin: false
		)
	]
}
