#!/usr/bin/env python3
"""Turn sites/*.yml into a Swift file the app compiles in.

The gallery has to work with no network and no YAML parser, and contributors have
to be able to add an entry without touching Swift. Generating the catalogue at
build-authoring time satisfies both: the source of truth stays a folder of small
YAML files, and the app ships a plain array.

Run after changing anything in sites/. CI checks the result is committed.
"""

import json
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
SITES = ROOT / "sites"
OUTPUT = ROOT / "Nifro" / "Sites" / "SiteCatalog.generated.swift"
INDEX = SITES / "index.json"

HEADER = """// Generated by Tools/generate-site-catalog.py from the YAML files under sites. Do not edit.
//
// Add or change a site by editing its YAML file and re-running the script.

import Foundation

extension SiteCatalog {
\tstatic let entries: [Entry] = [
"""

FOOTER = """\t]
}
"""


def swift_string(value: str) -> str:
    """A Swift string literal. JSON's escaping is a subset of Swift's for our purposes."""
    return json.dumps(value, ensure_ascii=False)


def swift_optional_string(value) -> str:
    return swift_string(value) if value else "nil"


def swift_zoom(zoom) -> str:
    if not zoom:
        return "nil"

    return (
        "Zoom(center: CGPoint(x: {centerX}, y: {centerY}), scale: {scale})".format(**zoom)
    )


def main() -> int:
    entries = []
    index = []

    for path in sorted(SITES.glob("*.yml")) + sorted(SITES.glob("*.yaml")):
        data = yaml.safe_load(path.read_text())

        index.append({
            "name": data["name"],
            "url": data["url"],
            "description": data["description"],
            "tags": data.get("tags", []),
            "reloadInterval": data.get("reloadInterval"),
            "zoom": data.get("zoom"),
            "css": data.get("css"),
            "javaScript": data.get("js") or data.get("javaScript"),
            "requiresLogin": bool(data.get("requiresLogin")),
            "audio": data.get("audio", "muted"),
            "featured": bool(data.get("featured")),
        })

        entries.append(
            "\t\t.init(\n"
            f"\t\t\tname: {swift_string(data['name'])},\n"
            f"\t\t\turl: {swift_string(data['url'])},\n"
            f"\t\t\tdescription: {swift_string(data['description'])},\n"
            f"\t\t\ttags: [{', '.join(swift_string(t) for t in data.get('tags', []))}],\n"
            f"\t\t\treloadInterval: {data.get('reloadInterval') or 'nil'},\n"
            f"\t\t\tzoom: {swift_zoom(data.get('zoom'))},\n"
            f"\t\t\tcss: {swift_optional_string(data.get('css'))},\n"
            f"\t\t\tjavaScript: {swift_optional_string(data.get('js') or data.get('javaScript'))},\n"
            f"\t\t\trequiresLogin: {'true' if data.get('requiresLogin') else 'false'},\n"
            f"\t\t\tplaysSound: {'true' if data.get('audio') == 'unmuted' else 'false'},\n"
            f"\t\t\tisFeatured: {'true' if data.get('featured') else 'false'}\n"
            "\t\t)"
        )

    if not entries:
        print("no site entries found", file=sys.stderr)
        return 1

    OUTPUT.write_text(HEADER + ",\n".join(entries) + "\n" + FOOTER)

    # The same data as JSON, served straight from the repo. The app fetches this so
    # entries contributed between releases reach people without an app update; the
    # Swift file above is only the offline fallback.
    INDEX.write_text(json.dumps(index, ensure_ascii=False, indent=1, sort_keys=True) + "\n")

    print(f"wrote {len(entries)} entries to {OUTPUT.relative_to(ROOT)} and {INDEX.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
